language: ruby
sudo: false
before_install:
    - gem install bundler
    - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
    - bundle update
    - psql -c 'create database propertyCross_test;' _U postgres
cache: bundler
addons:
    postgresql: "9.4"
